package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/tpe11etier/cloudcutter/internal/config"
	"gopkg.in/yaml.v3"
)

var (
	initForce bool
	initCmd   = &cobra.Command{
		Use:   "init",
		Short: "Generate ~/.cloudcutter/config.yaml from existing setup",
		Long: `Reads ~/.cloudcutter/opal.json, ~/.cloudcutter/dragos.json, and
relevant env vars, then writes ~/.cloudcutter/config.yaml. Refuses to
overwrite an existing config.yaml unless --force is given.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("could not resolve home directory: %w", err)
			}
			return runInit(home, initForce)
		},
	}
)

func init() {
	initCmd.Flags().BoolVar(&initForce, "force", false, "overwrite existing config.yaml")
	rootCmd.AddCommand(initCmd)
}

// runInit synthesizes ~/.cloudcutter/config.yaml from legacy configs
// under the given home directory. Exposed for testing.
func runInit(home string, force bool) error {
	cloudcutterDir := filepath.Join(home, ".cloudcutter")
	configPath := filepath.Join(cloudcutterDir, "config.yaml")

	if !force {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf("%s already exists; pass --force to overwrite", configPath)
		}
	}

	if err := os.MkdirAll(cloudcutterDir, 0o700); err != nil {
		return fmt.Errorf("mkdir %s: %w", cloudcutterDir, err)
	}

	cfg := config.Config{}
	if opalPath := filepath.Join(cloudcutterDir, "opal.json"); fileExists(opalPath) {
		if err := mergeLegacyOpal(opalPath, &cfg); err != nil {
			return err
		}
	}

	if dragosPath := filepath.Join(cloudcutterDir, "dragos.json"); fileExists(dragosPath) {
		if err := mergeLegacyDragos(dragosPath, &cfg, cloudcutterDir); err != nil {
			return err
		}
	}

	// If we collected nothing, fall back to the starter.
	if cfg.DefaultAWSBackend == nil && len(cfg.Environments) == 0 {
		return os.WriteFile(configPath, []byte(config.StarterYAML()), 0o600)
	}

	// Always include local; harmless and matches starter's helpfulness.
	cfg.Environments = append(cfg.Environments, config.EnvironmentSpec{
		Name: "local",
		Auth: config.AuthSpec{Type: "none"},
		Transport: config.TransportSpec{
			Type:    "plain",
			BaseURL: "http://localhost:9200",
		},
		TimeFields: []config.TimeField{},
	})

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return fmt.Errorf("marshal yaml: %w", err)
	}

	header := "# ~/.cloudcutter/config.yaml — generated by `cloudcutter init` from\n" +
		"# legacy ~/.cloudcutter/opal.json, ~/.cloudcutter/dragos.json, and env vars.\n" +
		"# Edit freely; cloudcutter does not regenerate this file unless you re-run\n" +
		"# `cloudcutter init --force`.\n\n"
	return os.WriteFile(configPath, append([]byte(header), out...), 0o600)
}

type legacyOpal struct {
	Environments map[string]struct {
		RoleID      string   `json:"roleId"`
		ProfileTags []string `json:"profileTags"`
	} `json:"environments"`
}

func mergeLegacyOpal(path string, cfg *config.Config) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	var legacy legacyOpal
	if err := json.Unmarshal(raw, &legacy); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}

	if cfg.DefaultAWSBackend == nil {
		cfg.DefaultAWSBackend = &config.EnvironmentTemplate{
			Vars: map[string][]config.VarRule{},
			Auth: config.AuthSpec{
				Type: "aws_sdk",
				PreAuth: &config.PreAuthSpec{
					Command: []string{
						"opal", "iam-roles:start", "--id", "{role_id}", "--profileName", "{profile}",
					},
					DetectSessionExpired: []string{
						"Enter your email",
						"session is invalid or expired",
					},
				},
			},
			Transport: config.TransportSpec{
				Type:        "sigv4",
				Service:     "es",
				URLTemplate: "https://{prefix}-{region}-primary-es.darkbytes.io",
			},
			IndexPattern: "main-summary-*",
			TimeFields: []config.TimeField{
				{Name: "unixTime", Format: "unix"},
				{Name: "detectionGeneratedTime", Format: "unix_ms"},
			},
		}
	}

	for envName, env := range legacy.Environments {
		// Pick a deterministic env-var name per env.
		envVarName := "OPAL_" + strings.ToUpper(envName) + "_ROLE_ID"

		for _, tag := range env.ProfileTags {
			matchExpr := "^" + tag + "$"
			cfg.DefaultAWSBackend.Vars["role_id"] = append(cfg.DefaultAWSBackend.Vars["role_id"], config.VarRule{
				Match: matchExpr,
				Env:   envVarName,
			})
			cfg.DefaultAWSBackend.Vars["prefix"] = append(cfg.DefaultAWSBackend.Vars["prefix"], config.VarRule{
				Match: matchExpr,
				Value: envName, // "dev", "prod" — matches the URL prefix
			})
		}
	}
	return nil
}

type legacyDragos struct {
	BaseURL      string `json:"baseUrl"`
	IndexPattern string `json:"indexPattern"`
	KbnVersion   string `json:"kbnVersion"`
	ProviderID   string `json:"providerId"`
	AuthToken    string `json:"authToken"`
}

func mergeLegacyDragos(path string, cfg *config.Config, cloudcutterDir string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	var legacy legacyDragos
	if err := json.Unmarshal(raw, &legacy); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}

	tokenPath := filepath.Join(cloudcutterDir, "dragos.token")
	if legacy.AuthToken != "" {
		if err := os.WriteFile(tokenPath, []byte(legacy.AuthToken), 0o600); err != nil {
			return fmt.Errorf("write token to %s: %w", tokenPath, err)
		}
	}

	indexPattern := legacy.IndexPattern
	if indexPattern == "" {
		indexPattern = "events*"
	}
	kbnVersion := legacy.KbnVersion
	if kbnVersion == "" {
		kbnVersion = "8.19.2"
	}
	providerID := legacy.ProviderID
	if providerID == "" {
		providerID = "00000000-0000-0000-0000-000000000002"
	}

	cfg.Environments = append(cfg.Environments, config.EnvironmentSpec{
		Name: "dragos",
		Auth: config.AuthSpec{
			Type: "jwt",
			Path: tokenPath,
			Env:  "DRAGOS_AUTH_TOKEN",
			Login: &config.LoginSpec{
				URL: legacy.BaseURL + "/auth/api/v1/login/password",
				BodyFields: []config.FormField{
					{Name: "username", Kind: "text"},
					{Name: "password", Kind: "password"},
				},
				Query: map[string]string{"providerId": providerID},
				TokenExtract: config.TokenExtractSpec{
					From: "cookie",
					Name: "dragos-auth-token",
				},
			},
		},
		Transport: config.TransportSpec{
			Type:      "kibana_proxy",
			BaseURL:   legacy.BaseURL,
			ProxyPath: "/kibana/api/console/proxy",
			TokenHeader: &config.TokenHeaderSpec{
				Name:   "Cookie",
				Format: "dragos-auth-token={token}",
			},
			Headers: map[string]string{
				"kbn-xsrf":    "cloudcutter",
				"kbn-version": kbnVersion,
			},
			Probe: &config.ProbeSpec{
				Path:       "_cluster/health",
				RejectHTML: true,
			},
		},
		IndexPattern: indexPattern,
		TimeFields: []config.TimeField{
			{Name: "createdAt", Format: "date"},
		},
	})
	return nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
